import type { Metadata } from "next";
import "./globals.css";
import classNames from "classnames";
import { dmSans } from "./assets";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Pixelo agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames(dmSans.className, "w-screen overflow-x-hidden")}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
